version: "3.2"
services:
  php-fpm:
    build:
      context: ./api
      dockerfile: ./tools/docker/php71-fpm/Dockerfile.local
    volumes:
      - type: volume
        source: ./api
        target: /var/www/html
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
    volumes:
      - type: volume
        source: ./api
        target: /var/www/html
    ports:
      - "8081:80"
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=M0mo1986
      - MYSQL_DATABASE=user
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api_pwd
    volumes:
      - /Users/mohamedkeita/mysql:/var/lib/mysql
  db-migration:
    build:
      context: ./api
      dockerfile: ./tools/docker/db-migration/Dockerfile
    command: ["./wait_for_it.sh", "db:3306", "--", "./tools/docker/db-migration/entrypoint.sh"]
    depends_on:
      - db

