version: "3.2"
services:
  php-fpm:
    image: momokeith/userletsgo-php-fpm
  api:
    image: momokeith/userletsgo-api
    environment:
      - VIRTUAL_HOST=user.api.letsgo.staging.kfina.net
    ports:
      - "8081:80"
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=M0mo1986
      - MYSQL_DATABASE=user
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api_pwd
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  db-migration:
    image: momokeith/db-migration
    depends_on:
      - db