- hosts: all
  become: true

  tasks:
    - name: Copy stack to swarm
      copy:
        src: /Users/mohamed.keita/Projects/Personal/user.letsgo/docker-stack.yml
        dest: ~

    - name: Deploy stack
      command: docker stack deploy -c ~/docker-stack.yml user_letsgo