docker_edition: 'ce'
docker_version: '17.06.2'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

docker_install_compose: true
docker_compose_version: "1.15.0"
docker_compose_path: /usr/local/bin/docker-compose